config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user do

      root 'users#show', as: :authenticated_root
    end

  unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :api do
    namespace :v1 do
      get '/lois' => 'lois#index'
      post '/lois/' => 'lois#create'
      get '/lois/:id' => 'lois#show'
      patch '/lois/:id' => 'lois#update'

      get '/invited_lois' => 'invited_lois#index'
      post '/invited_lois/' => 'invited_lois#create'
      get '/invited_lois/:id' => 'invited_lois#show'

      get '/invite_maxes' => 'invite_maxes#index'
      get '/invite_maxes/:id' => 'invite_maxes#show'


      get '/questions' => 'questions#index'
      get '/questions/:id' => 'questions#show'

      get '/sections' => 'sections#index'
      post '/answers' => 'answers#create'
      get '/answers' => 'answers#index'
      get '/ratings' => 'ratings#index'
      get '/ratings/yes_ratings' => 'ratings#yes_ratings'
      get '/ratings/:id' => 'ratings#show'
      patch 'ratings/:id.json' => 'ratings#update'

      get '/rfp_sections' => 'rfp_sections#index'
      post '/rfp_sections' => 'rfp_sections#create'
      patch '/rfp_sections/:id.json' => 'rfp_sections#update'

      get '/rfps' => 'rfps#index'
      get '/rfps/:id' => 'rfps#show'
      patch '/rfps/:id' => 'rfps#update'

      get '/rfp_questions' => 'rfp_questions#index'

      get '/rfp_ratings' => 'rfp_ratings#index'

      post '/attachments' => 'attachments#create'

      delete '/rfp_answers' => 'rfp_answers#destroy'

      delete '/sub_answers' => 'sub_answers#destroy'
    end
  end

  get '/home' => 'landings#home'
  get '/thanks/:id' => 'landings#thanks'

  get '/landings' => 'landings#index'
  get '/landings/edit' => 'landings#edit'
  get '/landings/:id' => 'landings#home'
  patch '/landings/:id' => 'landings#update'

  get '/ratings' => 'ratings#index'
  get '/ratings/new' => 'ratings#new'
  get '/ratings/:id' => 'ratings#show'
  post '/ratings' => 'ratings#create'
  get '/ratings/:id/edit' => 'ratings#edit'
  patch '/ratings/:id' => 'ratings#update'
  delete '/ratings/:id' => 'ratings#destroy'

  get '/questions' => 'questions#index'
  get '/questions/new' => 'questions#new'
  post '/questions' => 'questions#create'
  get '/questions/:id' => 'questions#show'
  get '/questions/:id/edit' => 'questions#edit'
  patch '/questions/:id' => 'questions#update'
  delete '/questions/:id' => 'questions#destroy'

  get '/users' => 'users#index'
  get '/users/:id' => 'users#show'
  patch '/users/:id' => 'users#update'

  get '/lois' => 'lois#index'
  get '/lois/new' => 'lois#new'
  post '/lois' => 'lois#create'
  get '/lois/:id' => 'lois#show'
  get '/lois/:id/edit' => 'lois#edit'
  patch '/lois/:id' => 'lois#update'
  delete '/lois/:id' => 'lois#destroy'

  get '/sections' => 'sections#index'
  get '/sections' => 'sections#new'
  get '/sections/:id' => 'sections#show'
  post '/sections' => 'sections#create'

  get '/rfps' => 'rfps#index'
  get '/rfps/new' => 'rfps#new'
  get '/rfps/:id' => 'rfps#show'
  get '/rfps/:id/edit' => 'rfps#edit'
  patch '/rfps/:id' => 'rfps#update'

  get '/rfp_ratings' => 'rfp_ratings#index'
  get '/rfp_ratings/new' => 'rfp_ratings#new'
  get '/rfp_ratings/:id' => 'rfp_ratings#show'
  post '/rfp_ratings' => 'rfp_ratings#create'
  get '/rfp_ratings/:id/edit' => 'rfp_ratings#edit'
  patch '/rfp_ratings/:id' => 'rfp_ratings#update'
  delete '/rfp_ratings/:id' => 'rfp_ratings#destroy'

  get '/rfp_questions' => 'rfp_questions#index'
  get '/rfp_questions/new' => 'rfp_questions#new'
  post '/rfp_questions' => 'rfp_questions#create'
  get '/rfp_questions/:id' => 'rfp_questions#show'
  get '/rfp_questions/:id/edit' => 'rfp_questions#edit'
  patch '/rfp_questions/:id' => 'rfp_questions#update'
  delete '/rfp_questions/:id' => 'rfp_questions#destroy'

  get '/attachments' => 'attachments#index'
  get '/attachments/new' => 'attachments#new'
  post '/attachments' => 'attachments#create'
  get '/attachments/:id' => 'attachments#show'
  delete '/attachments/:id' => 'attachments#destroy'

  get 'invite_maxes/:id/edit' => 'invite_maxes#edit'
  patch 'invite_maxes/:id' => 'invite_maxes#update'

  get '/rfp_sections/new' => 'rfp_sections#new'
  post '/rfp_sections' => 'rfp_sections#create'
  get '/rfp_sections/:id/edit' => 'rfp_sections#edit'
  patch '/rfp_sections/:id' => 'rfp_sections#update'
  delete '/rfp_sections/:id' => 'rfp_sections#destroy'

  get '/sub_questions/:id/edit' => 'sub_questions#edit'
  patch '/sub_questions/:id' => 'sub_questions#update'
  delete '/sub_questions/:id' => 'sub_questions#destroy'

  get '/emails' => 'emails#index'
  post '/emails' => 'emails#send_rejection_emails'

  patch '/dashboards/:id' => 'dashboards#update'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  # code below is for using Paperclip:
  # has_attached_file :attachment_file  
  # do_not_validate_attachment_file_type :attachment_file
  belongs_to :rfp
end

app/controllers/api/v1/attachments_controller.rb
class Api::V1::AttachmentsController < ApplicationController

  def index
    @attachments = Attachment.all
  end

  def create
    # Make an object in your bucket for your upload
    obj = S3_BUCKET.objects[params[:file].original_filename]

    # Upload the file
    obj.write(
      file: params[:file],
      acl: :public_read
    )
 

    # Create an object for the upload
    attachment = Attachment.create(
        url: obj.public_url,
        name: obj.key,
        user_id: params[:current_user],
        doc_type: params[:doc_type]
        )

    if params[:rfp_id]
      attachment.update(rfp_id: params[:rfp_id])
    end


    # Save the upload
    if attachment.save  
      render json: { message: "File Uploaded"}, status: 200
    else
      render json: { errors: @post.errors.full_messages }, status: 422
    end
  end

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :index]

  def index
    @attachments = current_user.admin ? Attachment.all : Attachment.where(user_id: current_user.id)
  end
  def show
    @attachment = Attachment.find_by(id: params[:id])
  end

  def new
    @rfps = current_user.admin ? Rfp.all : Rfp.where(user_id: current_user.id)
    @attachment = Attachment.new
  end

  def create

    # Make an object in your bucket for your upload
    obj = S3_BUCKET.objects[params[:file].original_filename]

    # Upload the file
    obj.write(
      file: params[:file],
      acl: :public_read
    )

    # Create an object for the upload
    @attachment = Attachment.new(
        url: obj.public_url,
        name: obj.key     
        )

    @attachment.rfp_id = params[:rfp_id]
    @attachment.user_id = Rfp.find(@attachment.rfp_id).user_id
    @attachment.doc_type = params[:doc_type]

    # Save the upload
    if @attachment.save
      redirect_to "/attachments/#{@attachment.id}", success: 'File successfully uploaded'
    else
      flash.now[:notice] = 'There was an error'
      render :new
    end
  end

  def destroy
    @attachment = Attachment.find_by(id: params[:id])
    rfp_id = @attachment.rfp_id
    @attachment.destroy

    flash[:warning] = "Attachment deleted"
    redirect_to "/rfps/#{rfp_id}"
  end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/index.html.erb
<div class="container">
  <div id="form-paper">
    <div class="form-heading">
      <h1>All Attachments</h1>
    </div>
    <div style="padding:30px;">
      <div class="form-horizontal">

        <table class="table">
          <% @attachments.each do |attachment| %>
            <tr>
              <td>
                <% if attachment.rfp %>
                  <%= attachment.rfp.org_name %>
                <% end %>
              </td>
              <td><%= link_to attachment.name, attachment.url %></td>
            </tr>
          <% end %>
        </table>

    </div>
    </div>
  </div>
</div>

app/views/attachments/new.html.erb
<div class="container">
  <div id="form-paper">
    <div class="form-heading">
      <h1>Add an attachment</h1>
    </div>
    <div style="padding:30px;">
      <div class="form-horizontal">

        <%= form_tag attachments_path, enctype: 'multipart/form-data' do %>
            <p>Select an RFP:</p>

            <%= select_tag 'rfp_id', options_for_select(@rfps.collect{ |u| [u.org_name, u.id] }) %>

            <p></p>

            <p>Enter Document Title:</p>
            <%= text_field_tag 'doc_type', nil, placeholder: 'Enter Document Title...' %>

            <p></p>

            <p>Select a file:</p>

            <%= file_field_tag :file  %>

            <p></p>
            <%= submit_tag 'Upload file' %>     
        <% end %>

    </div>
    </div>
  </div>
</div>

app/views/attachments/show.html.erb
<div class="container">
  <div id="form-paper">
    <div class="form-heading">
      <h1>Add an attachment</h1>
    </div>
    <div style="padding:30px;">
      <div class="form-horizontal">

        <h2>File Name: <%= @attachment.name %></h1>
        <h2>URL: <a href="<%= @attachment.url %>"><%= @attachment.url %></a></h2>

        <p> 
          <%= link_to "View #{@attachment.rfp.org_name}'s RFP", "/rfps/#{@attachment.rfp_id}" %>
           | 
          <%= link_to "Upload another attachment", "/attachments/new" %>
        </p>

    </div>
    </div>
  </div>
</div>